#!/usr/bin/env python3
"""
Reassembles games/blacksmith-tycoon-src/ back into the single-file
games/blacksmith-tycoon.html that is actually served/committed.

Do NOT hand-edit games/blacksmith-tycoon.html directly -- edit the source
files here and re-run this script (python3 build.py).

Reads index.html, inlines its <link rel="stylesheet"> and <script src>
references (in the order they appear in index.html -- that order is the
single source of truth for module load order), then rewrites asset paths
so they resolve correctly from games/blacksmith-tycoon.html's location
(one directory shallower than this src/ folder).
"""
import re
import pathlib

SRC_DIR = pathlib.Path(__file__).resolve().parent
OUT_FILE = SRC_DIR.parent / 'blacksmith-tycoon.html'

BANNER = (
    "<!-- AUTO-GENERATED by games/blacksmith-tycoon-src/build.py — "
    "edit the source files under blacksmith-tycoon-src/, not this file. -->\n"
)


def inline_css(match):
    href = match.group(1)
    css = (SRC_DIR / href).read_text(encoding='utf-8')
    # css/style.css is loaded via <link> in the dev shell, so its own url()s
    # resolve relative to the stylesheet's OWN path (two dirs below games/) --
    # once inlined into <style> here, they resolve relative to the HTML
    # document instead (one dir below games/), so strip one extra level.
    css = css.replace('../../assets/', 'assets/')
    return f'<style>\n{css}</style>'


def inline_js(match):
    src = match.group(1)
    js = (SRC_DIR / src).read_text(encoding='utf-8')
    return f'<script>\n{js}</script>'


def main():
    html = (SRC_DIR / 'index.html').read_text(encoding='utf-8')
    html = re.sub(r'<link rel="stylesheet" href="([^"]+)">', inline_css, html)
    html = re.sub(r'<script src="([^"]+)"></script>', inline_js, html)
    # Remaining `../assets/` references (raw HTML markup src= attributes, plus
    # any JS string literals referencing asset paths) were written relative to
    # index.html's own location (one dir below games/) -- one dir shallower here.
    html = html.replace('../assets/', 'assets/')
    OUT_FILE.write_text(BANNER + html, encoding='utf-8')
    print(f'Built {OUT_FILE} ({len(html)} bytes)')


if __name__ == '__main__':
    main()
